[Settings]
gtk-icon-theme-name=Papirus-Dark
gtk-theme-name=Adwaita-dark
gtk-font-name=JetBrainsMono Nerd Font 11
gtk-application-prefer-dark-theme=1

# Controles de ventana a la izquierda.
gtk-decoration-layout=close,minimize,maximize:menu
